export const SET_USER = 'SET_USER';
export const USERS_ERROR = 'USERS_ERROR';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';


export const LOAD_BANNER = 'LOAD_BANNER';
export const ADD_BANNER = 'ADD_BANNER';
export const BANNER_ERROR = 'BANNER_ERROR';
export const REMOVE_BANNER = 'REMOVE_BANNER';


export const LOAD_COUNTER = 'LOAD_COUNTER';
export const ADD_COUNTER = 'ADD_COUNTER';
export const UPDATE_COUNTER = 'UPDATE_COUNTER';
export const ERROR_COUNTER = 'ERROR_COUNTER';
export const REMOVE_COUNTER = 'REMOVE_COUNTER';


export const LOAD_ABOUT = 'LOAD_ABOUT';
export const CREATE_ABOUT = 'CREATE_ABOUT';
export const UPDATE_ABOUT = 'UPDATE_ABOUT';
export const ERROR_ABOUT = 'ERROR_ABOUT';
export const REMOVE_ABOUT = 'REMOVE_ABOUT';


export const LOAD_SOCIAL = 'LOAD_SOCIAL';
export const CREATE_SOCIAL = 'CREATE_SOCIAL';
export const UPDATE_SOCIAL = 'UPDATE_SOCIAL';
export const ERROR_SOCIAL = 'ERROR_SOCIAL';
export const REMOVE_SOCIAL = 'REMOVE_SOCIAL';


export const LOAD_CONTACT = 'LOAD_CONTACT';
export const CREATE_CONTACT = 'CREATE_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const ERROR_CONTACT = 'ERROR_CONTACT';
export const REMOVE_CONTACT = 'REMOVE_CONTACT';